import { isIpAllowed, getClientIp, parseIp } from "../../src/lib/crymad-crm/ip";
import { parseSignatureHeader, verifySignature, requestPayload, webhookPayload, buildSignatureHeader } from "../../src/lib/crymad-crm/crypto";
import { htmlToPlainText, safeDecode } from "../../src/lib/crymad-crm/text";
let pass = 0, fail = 0;
const check = (name: string, ok: boolean) => { ok ? pass++ : fail++; console.log(`${ok ? "PASS" : "FAIL"} ${name}`); };
check("ipv4 exact", isIpAllowed("203.0.113.7", ["203.0.113.7"]));
check("ipv4 cidr in", isIpAllowed("203.0.113.200", ["203.0.113.0/24"]));
check("ipv4 cidr out", !isIpAllowed("203.0.114.1", ["203.0.113.0/24"]));
check("ipv4 /0 matches all v4", isIpAllowed("8.8.8.8", ["0.0.0.0/0"]));
check("ipv4-mapped ipv6", isIpAllowed("::ffff:203.0.113.7", ["203.0.113.0/24"]));
check("ipv6 cidr in", isIpAllowed("2001:db8::1", ["2001:db8::/32"]));
check("ipv6 cidr out", !isIpAllowed("2001:db9::1", ["2001:db8::/32"]));
check("ipv6 full form equals compressed", parseIp("2001:0db8:0000:0000:0000:0000:0000:0001")?.value === parseIp("2001:db8::1")?.value);
check("v4 never matches v6 rule", !isIpAllowed("1.2.3.4", ["::/0"]));
check("garbage ip rejected", !isIpAllowed("not-an-ip", ["0.0.0.0/0"]));
check("bad octet rejected", parseIp("1.2.3.256") === null);
check("last XFF hop is trusted", getClientIp(new Headers({ "x-forwarded-for": "6.6.6.6, 203.0.113.7" })) === "203.0.113.7");
check("x-real-ip fallback", getClientIp(new Headers({ "x-real-ip": "203.0.113.9" })) === "203.0.113.9");
check("header parse multi v1", parseSignatureHeader(`t=123,v1=${"a".repeat(64)},v1=${"b".repeat(64)}`)?.v1.length === 2);
check("header parse rejects short v1", parseSignatureHeader("t=123,v1=abc") === null);
check("header parse needs t", parseSignatureHeader(`v1=${"a".repeat(64)}`) === null);
const now = Math.floor(Date.now() / 1000);
const body = Buffer.from('{"a":1}');
const pf = requestPayload("POST", "/crymad-crm/v1/actions/x?dry_run=true", body);
const hdr = buildSignatureHeader(["whsec_a"], pf(now), now);
check("request signature verifies", verifySignature(hdr, pf, ["whsec_b", "whsec_a"], now).ok);
check("tampered body fails", !verifySignature(hdr, requestPayload("POST", "/crymad-crm/v1/actions/x?dry_run=true", Buffer.from('{"a":2}')), ["whsec_a"], now).ok);
check("tampered query fails", !verifySignature(hdr, requestPayload("POST", "/crymad-crm/v1/actions/x", body), ["whsec_a"], now).ok);
const wp = webhookPayload(body);
check("webhook signature verifies", verifySignature(buildSignatureHeader(["whsec_a"], wp(now), now), wp, ["whsec_a"], now).ok);
check("window edge 300s ok", verifySignature(buildSignatureHeader(["whsec_a"], wp(now - 300), now - 300), wp, ["whsec_a"], now).ok);
check("301s expired", !verifySignature(buildSignatureHeader(["whsec_a"], wp(now - 301), now - 301), wp, ["whsec_a"], now).ok);
check("html to text keeps breaks", htmlToPlainText("<p>Hi</p><p>A &amp;lt; B<br>C</p>") === "Hi\nA &lt; B\nC");
check("html entities decoded once", htmlToPlainText("&amp;amp;") === "&amp;");
check("script tags stripped", !htmlToPlainText("<script>alert(1)</script>x").includes("<"));
check("safeDecode tolerates bad input", safeDecode("%E0%A4%A") === "%E0%A4%A");
console.log(`${pass} passed, ${fail} failed`);
process.exit(fail ? 1 : 0);
